[server]
maxUploadSize = 500
enableCORS = false
enableXsrfProtection = false

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#e74c3c"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6F9"
textColor = "#111111"
